### ISSUE TITLE
x.0 release checklist

### ISSUE THREAD

**Issue by sockheadrps** [sockheadrps/Terrace-Dashboard#23]
## x.0 release checklist
<br>

Meant to be an easier to parse version of the Bugs and Fix list issue, to get a broader idea of completion.

---------------------------------
### Front end
- [x] Home Page

- [ ] Settings
    - [x] Bookmarks
    - [x] Service Icons tool
    - [x] Weather API credentials

- [ ] Service Clients
    - [ ] Hardware Client ( Rust )
    - [ ] Hardware Client ( Python CLI )
    - [ ] Controller ( Python CLI, Media controls  | windows only )
---------------------------------

### Server
- [x] Login / Register
- [x] Protected routes
- [x] WS communication from clients routed to the correct user

---------------------------------
